name: CD

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 23
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle
        run: gradle build
      - name: Build Docker linux/arm64 image
        run: gradle bootBuildImage --imageName=maasmai/account --imagePlatform="linux/arm64" -PdockerUrl=docker.io/maasmai/account -PdockerUsername=${{ vars.DOCKERHUB_USERNAME }} -PdockerPassword=${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker linux/amd64 image
        run: gradle bootBuildImage --imageName=maasmai/account --imagePlatform="linux/amd64" -PdockerUrl=docker.io/maasmai/account -PdockerUsername=${{ vars.DOCKERHUB_USERNAME }} -PdockerPassword=${{ secrets.DOCKERHUB_TOKEN }}
